version: "3.6"

services:
    # Core configuration
    php:
        container_name: ${CONTAINER_NAME}_php-fpm
        build:
            args:
                WORKFOLDER: "${WORKFOLDER}"
            context: .
            target: base
        ports:
          - "${PHP_PORT}:9000"
        volumes:
            - "./:${WORKFOLDER}"
            - './docker/php/conf/dev/php.ini:/usr/local/etc/php/php.ini'
        links:
          - mysql
    # Server
    nginx:
        container_name: ${CONTAINER_NAME}_nginx
        image: nginx:latest
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - "./:${WORKFOLDER}"
            - ./docker/nginx/conf/dev/blog.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    # DB configuration
    mysql:
        container_name: ${CONTAINER_NAME}_mysql
        image: mysql:5.7
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_DATABASE: '${MYSQL_DBNAME}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
