-- MySQL Script generated by MySQL Workbench
-- Tue Sep 19 05:41:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydbblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydbblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydbblog` DEFAULT CHARACTER SET utf8 ;
USE `mydbblog` ;

-- -----------------------------------------------------
-- Table `mydbblog`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbblog`.`article` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `chapo` TEXT(800) NOT NULL,
  `auteur` VARCHAR(255) NOT NULL,
  `contenu` LONGTEXT NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_modification` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
